export default {
  type: 'object',
  properties: {
    nombre: { type: 'string' },
    genero: { type: 'string' },
    peliculas: { type: 'string' },
    color_ojo: { type: 'string' },
    color_cabello: { type: 'string' },
    color_piel: { type: 'string' },
    altura: { type: 'string' },
    peso: { type: 'string' },
    planeta_natal: { type: 'string' },
    especies: { type: 'string' },
    naves_estelares: { type: 'string' },
    vehiculos: { type: 'string' },
    url: { type: 'string' },
    fecha_nacimiento: { type: 'string' },
  },
  required: [
    'nombre',
    'genero',
    'peliculas',
    'color_ojo',
    'color_cabello',
    'color_piel',
    'altura',
    'peso',
    'planeta_natal',
    'especies',
    'naves_estelares',
    'vehiculos',
    'url',
    'fecha_nacimiento',
  ],
} as const
